db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
web:
  build: .
  command: python3 manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/app:z
  ports:
    - "9002:8000"
  links:
    - db
